name: Node.js CI

on:
  push:
    branches:
      - '*'  # This will trigger the workflow on pushes to any branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0' # Specify the Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Run Build
      run: npm run build

    - name: Run Tests
      run: npm test
