name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t litehost .

    - name: Save Docker image
      run: docker save litehost > litehost.tar

    - name: Copy Docker image to EC2
      uses: appleboy/scp-action@master
      with:
        host: ec2-18-191-82-62.us-east-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.LITEHOST_HOST_RSA_KEY }}
        source: "litehost.tar"
        target: "/tmp"

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ec2-18-191-82-62.us-east-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.LITEHOST_HOST_RSA_KEY }}
        script: |
          docker load < /tmp/litehost.tar
          echo "${{ secrets.dotenv_prod }}" > ~/secrets/.env.prod
          docker stop litehost || true
          docker run --rm -d -p 8080:3000 --name litehost -v $(pwd)/secrets:/usr/src/app/secrets litehost
