name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t litehost .

    - name: Save Docker image
      run: docker save litehost > litehost.tar

    - name: Copy docker image and secrets to EC2 instance
      env:
        SSH_PRIVATE_KEY: ${{ secrets.LITEHOST_HOST_RSA_KEY }}
        DOTENV_FILE: ${{ secrets.DOTENV_PROD }}
        FIREBASE_SVCACCOUNT_KEY: ${{ secrets.FIREBASE_SVCACCOUNT_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > mysshkey
        chmod 600 mysshkey
        scp -o StrictHostKeyChecking=no -i mysshkey litehost.tar ubuntu@ec2-18-217-17-33.us-east-2.compute.amazonaws.com:/tmp/litehost.tar
        mkdir secrets
        echo "$DOTENV_FILE" > secrets/.env.prod
        echo "$FIREBASE_SVCACCOUNT_KEY" > secrets/firebase-svcaccount-key.json
        scp -r -o StrictHostKeyChecking=no -i mysshkey secrets ubuntu@ec2-18-217-17-33.us-east-2.compute.amazonaws.com:~/
        


    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ec2-18-217-17-33.us-east-2.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.LITEHOST_HOST_RSA_KEY }}
        script: |
          sudo docker load < /tmp/litehost.tar
          sudo docker stop litehost
          sudo docker docker rm -f litehost
          sudo docker run --rm -d -p 8080:3000 --name litehost -v $(pwd)/secrets:/usr/src/app/secrets litehost
