name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t litehost .

    - name: Save Docker image
      run: docker save litehost > litehost.tar

    - name: Copy docker image and secrets to EC2 instance
      env:
        SSH_PRIVATE_KEY: ${{ secrets.LITEHOST_HOST_RSA_KEY }}
        DOTENV_FILE: ${{ secrets.DOTENV_PROD }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -o StrictHostKeyChecking=no litehost.tar ec2-user@ec2-18-191-82-62.us-east-2.compute.amazonaws.com:/tmp/litehost.tar
        mkdir secrets
        echo "$DOTENV_FILE" > secrets/.env.prod
        scp -o StrictHostKeyChecking=no secrets ec2-user@ec2-18-191-82-62.us-east-2.compute.amazonaws.com:~/secrets/
        


    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ec2-18-191-82-62.us-east-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.LITEHOST_HOST_RSA_KEY }}
        script: |
          docker load < /tmp/litehost.tar
          docker stop litehost || true
          docker run --rm -d -p 8080:3000 --name litehost -v $(pwd)/secrets:/usr/src/app/secrets litehost
